#!/usr/bin/env bash
#
# Neofetch user-config file

# Info to print
print_info() {
	info title
	info underline
	info "OS" distro
	info "Model" model
	info "Resoulution" resolution
	info "CPU" cpu
	info "GPU" gpu
	info "RAM" memory
	info "Kernel" kernel
	info "Packages" packages
	info "Shell" shell
	info "WM" wm
	info "Theme" theme
	info "Icons" icons
	info "Term" term
	info "Term Font" term_font
	info "Font" font
	info cols
}

kernel_shorthand="on"
distro_shorthand="on"
os_arch="on"
uptime_shorthand="on"
shell_path="off"
shell_version="on"
speed_type="bios_limit"
speed_shorthand="on"
cpu_shorthand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
gpu_type="all"
refresh_rate="on"
gtk_shorthand="on"
gtk2="on"
gtk3="on"
public_ip_host="http://ident.me"
disk_show=('/' '/home')
disk_subtitle="mount"
song_shorthand="off"
install_time="on"
install_time_format="12h"
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="—"
block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="w3m"
image_source="/home/alex/.config/feh/wall.png"
ascii_distro="arch"
ascii_colors=(distro)
ascii_bold="on"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=2
yoffset=0
xoffset=0
background_color=
scrot="off"
scrot_cmd="auto"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="teknik"

config_version="3.1.0"
